apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: assettoservermanager
build:
  artifacts:
    - image: assettoservermanager
      context: .
      docker:
        dockerfile: Dockerfile
    - image: assettoservermanager-config
      context: ./data/
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/k8s-pvc.yaml
      - k8s/k8s-pod.yaml
      - k8s/k8s-svc.yaml
profiles:
  - name: gcb
    deploy:
      kubectl:
        manifests:
          - k8s/managed-cert.yaml
          - k8s/load-balancer-backend-config.yaml
          - k8s/ingress.yaml

          - k8s/k8s-pvc.yaml
          - k8s/k8s-pod.yaml
          - k8s/k8s-svc.yaml
